export const inforCardList = [
  {
    imgUrl: "https://picsum.photos/200/300",
    title: "Evertop Hainanese Boneless Chicken",
    rate: 4.5,
    rateNumber: 25,
    followerNumber: 500,
    price: "$37.35",
    categories: ["Fast food", "Desserts"],
    tags: ["Hot deals", "Best sellers"],
    isVerified: true,
  },
  {
    imgUrl: "https://picsum.photos/200/300",
    title: "Evertop Hainanese Boneless Chicken",
    rate: 4.5,
    rateNumber: 25,
    followerNumber: 500,
    price: "$37.35",
    categories: ["Fast food", "Desserts"],
    tags: ["Hot deals", "Best sellers"],
    isVerified: false,
  },
  {
    imgUrl: "https://picsum.photos/200/300",
    title: "Evertop Hainanese Boneless Chicken",
    rate: 4.5,
    rateNumber: 25,
    followerNumber: 500,
    price: "$37.35",
    categories: ["Fast food", "Desserts"],
    tags: ["Hot deals", "Best sellers"],
    isVerified: true,
  },
  {
    imgUrl: "https://picsum.photos/200/300",
    title: "Evertop Hainanese Boneless Chicken",
    rate: 4.5,
    rateNumber: 25,
    followerNumber: 500,
    price: "$37.35",
    categories: ["Fast food", "Desserts"],
    tags: ["Hot deals", "Best sellers"],
  },
  {
    imgUrl: "https://picsum.photos/200/300",
    title: "Evertop Hainanese Boneless Chicken",
    rate: 4.5,
    rateNumber: 25,
    followerNumber: 500,
    price: "$37.35",
    categories: ["Fast food", "Desserts"],
    tags: ["Hot deals", "Best sellers"],
    isVerified: true,
  },
  {
    imgUrl: "https://picsum.photos/200/300",
    title: "Evertop Hainanese Boneless Chicken",
    rate: 4.5,
    rateNumber: 25,
    followerNumber: 500,
    price: "$37.35",
    categories: ["Fast food", "Desserts"],
    tags: ["Hot deals", "Best sellers"],
    isVerified: true,
  },
  {
    imgUrl: "https://picsum.photos/200/300",
    title: "Evertop Hainanese Boneless Chicken",
    rate: 4.5,
    rateNumber: 25,
    followerNumber: 500,
    price: "$37.35",
    categories: ["Fast food", "Desserts"],
    tags: ["Hot deals", "Best sellers"],
    isVerified: true,
  },
  {
    imgUrl: "https://picsum.photos/200/300",
    title: "Evertop Hainanese Boneless Chicken",
    rate: 4.5,
    rateNumber: 25,
    followerNumber: 500,
    price: "$37.35",
    categories: ["Fast food", "Desserts"],
    tags: ["Hot deals", "Best sellers"],
    isVerified: true,
  },
  {
    imgUrl: "https://picsum.photos/200/300",
    title: "Evertop Hainanese Boneless Chicken",
    rate: 4.5,
    rateNumber: 25,
    followerNumber: 500,
    price: "$37.35",
    categories: ["Fast food", "Desserts"],
    tags: ["Hot deals", "Best sellers"],
    isVerified: true,
  },
];

export const interestingList = [
  { avatar: "https://picsum.photos/200/300", label: "Animal" },
  { avatar: "https://picsum.photos/200/300", label: "Spicy" },
  { avatar: "https://picsum.photos/200/300", label: "DIY" },
  { avatar: "https://picsum.photos/200/300", label: "Festival" },
  { avatar: "https://picsum.photos/200/300", label: "Anime" },
  { avatar: "https://picsum.photos/200/300", label: "Hot food" },
  { avatar: "https://picsum.photos/200/300", label: "Travel" },
  { avatar: "https://picsum.photos/200/300", label: "Ice cream" },
  { avatar: "https://picsum.photos/200/300", label: "Shopping" },
];
