export const inforCardList = [
  {
    imgUrl: "https://picsum.photos/200/300",
    title: "Evertop Hainanese Boneless Chicken",
    rate: 4.5,
    rateNumber: 25,
    followerNumber: 500,
    price: "$37.35",
    categories: ["Fast food", "Desserts"],
    tags: ["Hot deals", "Best sellers"],
    isVerified: true,
  },
  {
    imgUrl: "https://picsum.photos/200/300",
    title: "Evertop Hainanese Boneless Chicken",
    rate: 4.5,
    rateNumber: 25,
    followerNumber: 500,
    price: "$37.35",
    categories: ["Fast food", "Desserts"],
    tags: ["Hot deals", "Best sellers"],
    isVerified: false,
  },
  {
    imgUrl: "https://picsum.photos/200/300",
    title: "Evertop Hainanese Boneless Chicken",
    rate: 4.5,
    rateNumber: 25,
    followerNumber: 500,
    price: "$37.35",
    categories: ["Fast food", "Desserts"],
    tags: ["Hot deals", "Best sellers"],
    isVerified: true,
  },
  {
    imgUrl: "https://picsum.photos/200/300",
    title: "Evertop Hainanese Boneless Chicken",
    rate: 4.5,
    rateNumber: 25,
    followerNumber: 500,
    price: "$37.35",
    categories: ["Fast food", "Desserts"],
    tags: ["Hot deals", "Best sellers"],
  },
  {
    imgUrl: "https://picsum.photos/200/300",
    title: "Evertop Hainanese Boneless Chicken",
    rate: 4.5,
    rateNumber: 25,
    followerNumber: 500,
    price: "$37.35",
    categories: ["Fast food", "Desserts"],
    tags: ["Hot deals", "Best sellers"],
    isVerified: true,
  },
];
