export const mealOptions = [
  { label: "Breakfast" },
  { label: "Brunch" },
  { label: "Late night" },
  { label: "Drinks" },
  { label: "Lunch" },
  { label: "Dinner" },
];

export const placeGoodFor = [
  { label: "Business Meetings" },
  { label: "Large Groups" },
  { label: "Families with Children" },
  { label: "Local Cuisine" },
  { label: "Hidden Gems" },
  { label: "Romantic" },
  { label: "Hot New Restaurants" },
  { label: "Scenic View" },
  { label: "Kids" },
  { label: "Special Occations" },
];

export const parkingNearby = [
  { label: "Street Parking" },
  { label: "Valet Parking" },
  { label: "Validated Parking" },
  { label: "Parking Available" },
  { label: "Free Off-Street Parking" },
];

export const atmosphere = [
  { label: "Beach" },
  { label: "Outdoor Seating" },
  { label: "Watergront" },
  { label: "Highchairs Available" },
  { label: "Live Music" },
  { label: "Non-smoking Restaurants" },
  { label: "Playground" },
  { label: "Private Dining" },
  { label: "Television" },
  { label: "Seating" },
];

export const paymentMethods = [
  { label: "Accepts Credit Cards" },
  { label: "Accepts Discover" },
  { label: "Accepts Visa" },
  { label: "Accepts American Express" },
  { label: "Accepts Mastercard" },
  { label: "Cash Only" },
  { label: "Digital Payment" },
];

export const additionalFeatures = [
  { label: "Delivery" },
  { label: "Gift Cards Availale" },
  { label: "Drive Thru" },
  { label: "Reservations" },
  { label: "Buffet" },
  { label: "Takeout" },
  { label: "Family style" },
  { label: "Wheelchair Accessible" },
  { label: "Serves Alcohol" },
  { label: "BYOB" },
  { label: "Jazz Bar" },
  { label: "prayer facility available/nearby" },
  { label: "Free Wifi" },
  { label: "wudu facilities available/nearby" },
];

export const cuisineModalList = [
  { label: "Afghani African" },
  { label: "Albanian" },
  { label: "Algerian" },
  { label: "American" },
  { label: "Apulian" },
  { label: "Arabic" },
  { label: "Argentinean" },
  { label: "Armenian" },
  { label: "Asian" },
  { label: "Assyrian" },
  { label: "Australian" },
  { label: "Austrian" },
  { label: "Azbaijani" },
  { label: "Bahamian" },
  { label: "Balti" },
  { label: "Bangladeshi" },
  { label: "Bar" },
  { label: "Barbecue" },
  { label: "Belgian" },
  { label: "Brazilian" },
  { label: "British" },
  { label: "Burmese" },
  { label: "Cafe" },
  { label: "Caju & Creole" },
  { label: "Calabrian" },
  { label: "Cambodian" },
  { label: "Campania" },
  { label: "Canadian" },
  { label: "Caribbean" },
  { label: "Catalan" },
  { label: "Caucasian" },
  { label: "Central American" },
  { label: "Central Asian" },
  { label: "Central European" },
  { label: "Central-Italian" },
  { label: "Chilean" },
];
