name: Master CI/CD

on:
  push:
    branches: [master]
jobs:
  build_push_deploy:
    env:
      DEPLOYMENT: 'tribes-frontend'

      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      DOCKER_REPO: 'eastplayers'
      DOCKER_IMAGE: 'tribes-frontend'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./deployment/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}/${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_REPO }}/${{ env.DOCKER_IMAGE }}:0.1.${{github.run_number}}
      - name: Deploy to cluster
        uses: Foxhound401/k8s-rollout-action@v0.1.8
        with:
          server-url: ${{ env.SERVER_URL }}
          token: ${{ env.TOKEN }}
          deployment: ${{ env.DEPLOYMENT }}
          image-name: ${{ env.IMAGE_NAME }}
          namespace: 'staging'
          container-name: ${{ env.DEPLOYMENT }}
